package kfx

import (
	"context"
	"fmt"
	"html"
	"strings"
	"unicode/utf8"
)

// Tags and attributes are generated by the reader. Source strings are always
// text. Positions stay in source Unicode code points until final serialization.
type element struct {
	tag, text    string
	attrs        []attribute
	children     []*element
	inlineObject bool // One position in its parent, its own text positions inside.
}
type attribute struct{ name, value string }

func (e *element) attr(name, value string) {
	if value == "" {
		return
	}
	for i := range e.attrs {
		if e.attrs[i].name == name {
			e.attrs[i].value = value
			return
		}
	}
	e.attrs = append(e.attrs, attribute{name, value})
}

func (e *element) attribute(name string) string {
	for _, a := range e.attrs {
		if a.name == name {
			return a.value
		}
	}
	return ""
}

func (e *element) void() bool { return e.tag == "img" || e.tag == "hr" || e.tag == "br" }

func (e *element) structured() bool {
	switch e.tag {
	case "table", "thead", "tbody", "tfoot", "tr", "ol", "ul":
		return true
	}
	return false
}

func (e *element) phrasing() bool {
	switch e.tag {
	case "", "span", "img", "br", "ruby", "rt":
		return true
	case "a":
		for _, child := range e.children {
			if !child.phrasing() {
				return false
			}
		}
		return true
	}
	return false
}

func (e *element) hasLink() bool {
	if e.tag == "a" {
		return true
	}
	for _, child := range e.children {
		if child.hasLink() {
			return true
		}
	}
	return false
}

type xhtmlWriter struct {
	ctx                              context.Context
	text                             strings.Builder
	lineStart, space, carriageReturn bool
}

func renderBody(ctx context.Context, root *element) (string, error) {
	w := xhtmlWriter{ctx: ctx, lineStart: true}
	if err := w.element(root); err != nil {
		return "", err
	}
	return w.text.String(), nil
}

func (w *xhtmlWriter) write(s string) error {
	if len(s) > maxGeneratedBytes-w.text.Len() {
		return fmt.Errorf("%w: generated XHTML is too large", ErrLimit)
	}
	w.text.WriteString(s)
	return nil
}

func (w *xhtmlWriter) element(e *element) error {
	if err := w.ctx.Err(); err != nil {
		return err
	}
	if e.tag == "rt" {
		lineStart, space, carriageReturn := w.lineStart, w.space, w.carriageReturn
		w.lineStart, w.space, w.carriageReturn = true, false, false
		defer func() { w.lineStart, w.space, w.carriageReturn = lineStart, space, carriageReturn }()
	}
	if e.tag == "" {
		return w.content(e.text)
	}
	block := !e.inlineObject && !e.phrasing() && !e.void()
	if block || e.tag == "br" || e.tag == "hr" {
		w.lineStart, w.space, w.carriageReturn = true, false, false
	} else if e.tag == "img" {
		w.lineStart, w.space, w.carriageReturn = false, false, false
	}
	if err := w.write("<" + e.tag); err != nil {
		return err
	}
	for _, a := range e.attrs {
		// Check the escaped size before allocating the escaped string.
		if escapedSize(a.value) > maxGeneratedBytes-w.text.Len()-len(a.name)-4 {
			return fmt.Errorf("%w: generated XHTML attribute is too large", ErrLimit)
		}
		if err := w.write(" " + a.name + `="` + html.EscapeString(a.value) + `"`); err != nil {
			return err
		}
	}
	if e.void() {
		return w.write("/>")
	}
	if err := w.write(">"); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := w.element(child); err != nil {
			return err
		}
	}
	if block {
		w.lineStart, w.space, w.carriageReturn = true, false, false
	} else if e.inlineObject && !e.phrasing() {
		w.lineStart, w.space, w.carriageReturn = false, false, false
	}
	return w.write("</" + e.tag + ">")
}

// Match html.EscapeString without allocating the escaped output.
func escapedSize(text string) int {
	size := len(text)
	for _, r := range text {
		switch r {
		case '&', '\'', '"':
			size += 4
		case '<', '>':
			size += 3
		}
	}
	return size
}

// KFX strings have already been laid out as reading text: line separators and
// repeated spaces are meaningful. Convert them only after locating anchors and
// style ranges, including ranges split across inline elements.
func (w *xhtmlWriter) content(text string) error {
	begin, checked := 0, 0
	for i, r := range text {
		if i-checked >= 4096 {
			if err := w.ctx.Err(); err != nil {
				return err
			}
			checked = i
		}
		replacement := ""
		skip := r == '\n' && w.carriageReturn
		w.carriageReturn = r == '\r'
		switch r {
		case '\n', '\r', '\u2028', '\u2029':
			replacement = "<br/>"
			w.lineStart, w.space = true, false
		case ' ':
			if w.lineStart || w.space || i+1 < len(text) && text[i+1] == ' ' {
				replacement = "\u00a0"
			}
			w.space = true
		default:
			w.lineStart, w.space = false, false
			switch r {
			case '&':
				replacement = "&amp;"
			case '<':
				replacement = "&lt;"
			case '>':
				replacement = "&gt;"
			}
		}
		if replacement != "" || skip {
			if err := w.write(text[begin:i]); err != nil {
				return err
			}
			if !skip {
				if err := w.write(replacement); err != nil {
					return err
				}
			}
			begin = i + utf8.RuneLen(r)
		}
	}
	return w.write(text[begin:])
}
