package koreader

import (
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"io"
	"os"
)

const (
	partialMD5Step       = 1024
	partialMD5SampleSize = 1024
)

// PartialMD5 computes KOReader's util.partialMD5 document identifier.
//
// KOReader samples 1024-byte chunks at LuaJIT bit-shift positions generated by
// 1024 << (2*i), i=-1..10. The negative first shift wraps to 0 in LuaJIT's
// 32-bit bitops, so the sampled offsets are 0, 1K, 4K, 16K, ..., 1G. The hash is
// only an identity key for sync, not a security primitive.
func PartialMD5(r io.ReadSeeker) (string, error) {
	h := md5.New() //nolint:gosec // KOReader protocol identity hash, not security.
	buf := make([]byte, partialMD5SampleSize)

	for i := -1; i <= 10; i++ {
		shift := uint((2 * i) & 0x1f)
		offset := int64(uint32(partialMD5Step) << shift)
		if _, err := r.Seek(offset, io.SeekStart); err != nil {
			return "", fmt.Errorf("seek sample: %w", err)
		}
		n, err := r.Read(buf)
		if n > 0 {
			if _, writeErr := h.Write(buf[:n]); writeErr != nil {
				return "", fmt.Errorf("hash sample: %w", writeErr)
			}
		}
		if err == io.EOF || n == 0 {
			break
		}
		if err != nil {
			return "", fmt.Errorf("read sample: %w", err)
		}
	}

	return hex.EncodeToString(h.Sum(nil)), nil
}

func PartialMD5File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("open file: %w", err)
	}
	defer f.Close()
	return PartialMD5(f)
}
